# -*- coding: utf-8 -*-
"""merge_importe_excel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1knasUcJtL4EwF-RfxK0K3mmhx_vBo0Ja
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as mp
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
#Importação do arquivo em excel
df1 = pd.read_excel("dados.xlsx", encoding = "UTF-8") 

df1 = df1.T.reset_index().rename(columns={"index":"mês"})
d1 = df1.shift(-1)
d1

d1 = d1.loc[0:11]
d1

d1.columns

d1.rename(columns={'mês':'index', 0 :'mês', 1 :'realizado'}, inplace=True)

d1.columns

d2 = pd.read_excel("dados.xlsx", "orcado")
d2.head(3)

d3 = pd.merge(d1, d2, on="mês", how="outer")
d3.head(3)

type(d3.realizado)

type(d3.orcado)

d3['diferenca'] = d3['orcado'] - d3['realizado']

d4 = d3[["mês", "orcado", "realizado", "diferenca"]]

d4

d4.to_dense().to_csv('dados-saida.csv', sep=';', index=False, encoding='utf-8-sig')

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

bar1 = np.arange(0, 81, 10)
print((bar1))

bar1 = np.arange(0, 81, 10)
print((bar1))

fig = plt.figure(figsize=(14,5))

N = 12
ListProfit = d4['diferenca']
ListDone = d4['realizado']
#difference = d4['diferenca']

ind = np.arange(N)
width = 0.7  

#plt.figure().set_figwidth(25)
p1 = plt.bar(ind, ListProfit, width, bottom=ListDone, label='Orçado')
p2 = plt.bar(ind, ListDone, width, label='Realizado')
plt.legend((p1[0], p2[0]), ('Orçado', 'Realizado'))

plt.xlabel('Mes')
plt.ylabel('$')
plt.title('Gráfico Orçamento')
plt.xticks(ind, d4['mês'])
plt.yticks(np.arange(0, 450, 100))

plt.legend()

plt.savefig('graficoAnalitico.png', dpi=100)

plt.show()